name: Continuous Integration
on:
  push:
    branches:
    - main
  schedule:
  - cron: "5 0 * * *" # TODO: Run every 4 hours to soak test, should be less frequent before merge (weekly/daily/???)
  workflow_dispatch:
env:
  IMAGE_NAME: cluster-api-provider-packet
  GHCR_REGISTRY: ghcr.io/${{ github.repository_owner }}
  DOCKER_REGISTRY: ${{ secrets.DOCKER_ORG }}
  QUAY_REGISTRY: quay.io/${{ secrets.QUAY_ORG }}
  REGISTRY: quay.io/${{ secrets.QUAY_ORG }}
  metadata_flavor: latest=false
  metadata_tags: type=sha

jobs:
  validate:
    name: "Validate ${{ matrix.target }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ["verify", "lint", "test"]
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v4
      with: 
        go-version-file: './go.mod'
    - uses: actions/cache@v3
      with:
        path: hack/tools/bin
        key: ${{ runner.os }}-tools-bin-${{ matrix.target }}-${{ hashFiles('Makefile') }}
        restore-keys: |
          ${{ runner.os }}-tools-bin-${{ matrix.target }}-
          ${{ runner.os }}-tools-bin-
    - uses: actions/cache@v3
      if: ${{ matrix.target == 'test' }}
      with:
        path: /tmp/kubebuilder-tools-*.tar.gz
        key: ${{ runner.os }}-tmp-${{ matrix.target }}-${{ hashFiles('scripts/fetch_ext_bins.sh') }}
        restore-keys: |
          ${{ runner.os }}-tmp-${{ matrix.target }}-
          ${{ runner.os }}-tmp-
    - name: ${{ matrix.target }}
      run: make ${{ matrix.target }}

  manager-image:
    name: Build and push manager image
    runs-on: ubuntu-latest
    needs:
    - validate
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with: 
        go-version-file: './go.mod'
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Generate metadata
      id: meta
      uses: ./.github/actions/metadata
      with:
        docker_username: ${{ secrets.DOCKER_USERNAME }}
        quay_username: ${{ secrets.QUAY_USERNAME }}
        metadata_flavor: ${{ env.metadata_flavor }}
        metadata_tags: ${{ env.metadata_tags }}

    - name: Log in to ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Log into DockerHub
      uses: docker/login-action@v2
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      if: ${{ env.DOCKER_USERNAME != '' }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Log into quay.io
      uses: docker/login-action@v2
      env:
        QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      if: ${{ env.QUAY_USERNAME != '' }}
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Build and push manager image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha, scope=${{ github.workflow }}
        cache-to: type=gha, mode=max, scope=${{ github.workflow }}

  test-release:
    name: Test Release
    runs-on: ubuntu-latest
    needs:
    - validate
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with: 
        go-version-file: './go.mod'
    - uses: actions/cache@v3
      with:
        path: hack/tools/bin
        key: ${{ runner.os }}-tools-bin-release-${{ hashFiles('Makefile') }}
        restore-keys: |
          ${{ runner.os }}-tools-bin-release-
          ${{ runner.os }}-tools-bin-

    - name: Generate metadata
      id: meta
      uses: ./.github/actions/metadata
      with:
        docker_username: ${{ secrets.DOCKER_USERNAME }}
        quay_username: ${{ secrets.QUAY_USERNAME }}
        metadata_flavor: ${{ env.metadata_flavor }}
        metadata_tags: ${{ env.metadata_tags }}

    - name: Test Release
      env:
        TAG: ${{ steps.meta.outputs.version }}
      run: make release
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: test-release
        path: out/release

  e2e-quickstart:
    name: "E2E quickstart"
    concurrency: ci-${{ github.ref }}-e2e-quickstart
    runs-on: ubuntu-latest
    needs:
    - manager-image
    - test-release
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with: 
        go-version-file: './go.mod'
    - uses: actions/cache@v3
      with:
        path: hack/tools/bin
        key: ${{ runner.os }}-tools-bin-e2e-${{ hashFiles('Makefile') }}
        restore-keys: |
          ${{ runner.os }}-tools-bin-e2e-
          ${{ runner.os }}-tools-bin-
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: test-release
        path: out/release

    - name: Generate metadata
      id: meta
      uses: ./.github/actions/metadata
      with:
        docker_username: ${{ secrets.DOCKER_USERNAME }}
        quay_username: ${{ secrets.QUAY_USERNAME }}
        metadata_flavor: ${{ env.metadata_flavor }}
        metadata_tags: ${{ env.metadata_tags }}

    - name: Prepull the pre-built image
      run: docker pull ${REGISTRY}/${IMAGE_NAME}:${TAG}
      env:
        TAG: ${{ steps.meta.outputs.version }}
    - name: "e2e-quickstart"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ steps.meta.outputs.version }}
        PACKET_API_KEY: ${{ secrets.PACKET_API_TOKEN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        E2E_CONF_FILE_SOURCE: "${{ github.workspace }}/test/e2e/config/packet-ci-actions.yaml"
        SKIP_IMAGE_BUILD: "1"
        MANIFEST_PATH: "../../../out/release"
        METRO: da
        CONTROLPLANE_NODE_TYPE: c3.medium.x86
        WORKER_NODE_TYPE: c3.medium.x86
        GINKGO_NODES: "1"
      run: ./scripts/ci-e2e-capi-quickstart.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: e2e-quickstart
        path: _artifacts
  e2e:
    name: "E2E"
    concurrency: ci-${{ github.ref }}-e2e
    runs-on: ubuntu-latest
    needs:
    - manager-image
    - test-release
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with: 
        go-version-file: './go.mod'
    - uses: actions/cache@v3
      with:
        path: hack/tools/bin
        key: ${{ runner.os }}-tools-bin-e2e-${{ hashFiles('Makefile') }}
        restore-keys: |
          ${{ runner.os }}-tools-bin-e2e-
          ${{ runner.os }}-tools-bin-
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: test-release
        path: out/release

    - name: Generate metadata
      id: meta
      uses: ./.github/actions/metadata
      with:
        docker_username: ${{ secrets.DOCKER_USERNAME }}
        quay_username: ${{ secrets.QUAY_USERNAME }}
        metadata_flavor: ${{ env.metadata_flavor }}
        metadata_tags: ${{ env.metadata_tags }}

    - name: Prepull the pre-built image
      run: docker pull ${REGISTRY}/${IMAGE_NAME}:${TAG}
      env:
        TAG: ${{ steps.meta.outputs.version }}
    - name: "e2e"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ steps.meta.outputs.version }}
        PACKET_API_KEY: ${{ secrets.PACKET_API_TOKEN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        E2E_CONF_FILE_SOURCE: "${{ github.workspace }}/test/e2e/config/packet-ci-actions.yaml"
        SKIP_IMAGE_BUILD: "1"
        MANIFEST_PATH: "../../../out/release"
        METRO: da
        CONTROLPLANE_NODE_TYPE: c3.medium.x86
        WORKER_NODE_TYPE: c3.medium.x86
        GINKGO_NODES: "1"
      run: ./scripts/ci-e2e-capi.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: e2e
        path: _artifacts
  e2e-conformance:
    name: "E2E conformance"
    concurrency: ci-${{ github.ref }}-e2e-conformance
    runs-on: ubuntu-latest
    needs:
    - manager-image
    - test-release
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with: 
        go-version-file: './go.mod'
    - uses: actions/cache@v3
      with:
        path: hack/tools/bin
        key: ${{ runner.os }}-tools-bin-e2e-${{ hashFiles('Makefile') }}
        restore-keys: |
          ${{ runner.os }}-tools-bin-e2e-
          ${{ runner.os }}-tools-bin-
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: test-release
        path: out/release

    - name: Generate metadata
      id: meta
      uses: ./.github/actions/metadata
      with:
        docker_username: ${{ secrets.DOCKER_USERNAME }}
        quay_username: ${{ secrets.QUAY_USERNAME }}
        metadata_flavor: ${{ env.metadata_flavor }}
        metadata_tags: ${{ env.metadata_tags }}

    - name: Prepull the pre-built image
      run: docker pull ${REGISTRY}/${IMAGE_NAME}:${TAG}
      env:
        TAG: ${{ steps.meta.outputs.version }}
    - name: "e2e-conformance"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ steps.meta.outputs.version }}
        PACKET_API_KEY: ${{ secrets.PACKET_API_TOKEN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        E2E_CONF_FILE_SOURCE: "${{ github.workspace }}/test/e2e/config/packet-ci-actions.yaml"
        SKIP_IMAGE_BUILD: "1"
        MANIFEST_PATH: "../../../out/release"
        METRO: da
        CONTROLPLANE_NODE_TYPE: c3.medium.x86
        WORKER_NODE_TYPE: c3.medium.x86
        GINKGO_NODES: "1"
      run: ./scripts/ci-e2e-capi-conformance.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: e2e-conformance
        path: _artifacts
  e2e-management-upgrade:
    name: "E2E Management-Upgrade"
    concurrency: ci-${{ github.ref }}-e2e-management-upgrade
    runs-on: ubuntu-latest
    needs:
    - manager-image
    - test-release
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with: 
        go-version-file: './go.mod'
    - uses: actions/cache@v3
      with:
        path: hack/tools/bin
        key: ${{ runner.os }}-tools-bin-e2e-${{ hashFiles('Makefile') }}
        restore-keys: |
          ${{ runner.os }}-tools-bin-e2e-
          ${{ runner.os }}-tools-bin-
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: test-release
        path: out/release

    - name: Generate metadata
      id: meta
      uses: ./.github/actions/metadata
      with:
        docker_username: ${{ secrets.DOCKER_USERNAME }}
        quay_username: ${{ secrets.QUAY_USERNAME }}
        metadata_flavor: ${{ env.metadata_flavor }}
        metadata_tags: ${{ env.metadata_tags }}

    - name: Prepull the pre-built image
      run: docker pull ${REGISTRY}/${IMAGE_NAME}:${TAG}
      env:
        TAG: ${{ steps.meta.outputs.version }}
    - name: "e2e-management-upgrade"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ steps.meta.outputs.version }}
        PACKET_API_KEY: ${{ secrets.PACKET_API_TOKEN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        E2E_CONF_FILE_SOURCE: "${{ github.workspace }}/test/e2e/config/packet-ci-actions.yaml"
        SKIP_IMAGE_BUILD: "1"
        MANIFEST_PATH: "../../../out/release"
        METRO: da
        CONTROLPLANE_NODE_TYPE: c3.medium.x86
        WORKER_NODE_TYPE: c3.medium.x86
        GINKGO_NODES: "1"
      run: ./scripts/ci-e2e-capi-management-upgrade.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: e2e-management-upgrade
        path: _artifacts
  e2e-workload-upgrade:
    name: "E2E Workload-Upgrade"
    concurrency: ci-${{ github.ref }}-e2e-workload-upgrade
    runs-on: ubuntu-latest
    needs:
    - manager-image
    - test-release
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with: 
        go-version-file: './go.mod'
    - uses: actions/cache@v3
      with:
        path: hack/tools/bin
        key: ${{ runner.os }}-tools-bin-e2e-${{ hashFiles('Makefile') }}
        restore-keys: |
          ${{ runner.os }}-tools-bin-e2e-
          ${{ runner.os }}-tools-bin-
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: test-release
        path: out/release

    - name: Generate metadata
      id: meta
      uses: ./.github/actions/metadata
      with:
        docker_username: ${{ secrets.DOCKER_USERNAME }}
        quay_username: ${{ secrets.QUAY_USERNAME }}
        metadata_flavor: ${{ env.metadata_flavor }}
        metadata_tags: ${{ env.metadata_tags }}

    - name: Prepull the pre-built image
      run: docker pull ${REGISTRY}/${IMAGE_NAME}:${TAG}
      env:
        TAG: ${{ steps.meta.outputs.version }}
    - name: "e2e-workload-upgrade"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ steps.meta.outputs.version }}
        PACKET_API_KEY: ${{ secrets.PACKET_API_TOKEN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        E2E_CONF_FILE_SOURCE: "${{ github.workspace }}/test/e2e/config/packet-ci-actions.yaml"
        SKIP_IMAGE_BUILD: "1"
        MANIFEST_PATH: "../../../out/release"
        METRO: da
        CONTROLPLANE_NODE_TYPE: c3.medium.x86
        WORKER_NODE_TYPE: c3.medium.x86
        GINKGO_NODES: "1"
      run: ./scripts/ci-e2e-capi-workload-upgrade.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: e2e-workload-upgrade
        path: _artifacts
