name: Pull Request Validation
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  validate:
    name: "Validate ${{ matrix.target }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ["verify", "lint", "test"]

    steps:

    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v4
      with: 
        go-version-file: './go.mod'

    - name: ${{ matrix.target }}
      run: make ${{ matrix.target }}